{
 "title": "RocketMQ / RocketMQ服务看板",
 "description": "Monitor RocketMQ by Prometheus, use RocketMQ Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "busigroup",
    "query": {
     "query": "label_values(rocketmq_broker_tps,busigroup)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(rocketmq_broker_tps{busigroup=\"$busigroup\"},cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "服务端", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Broker级别的消费QPS",
   "type": "timeseries",
   "description": "Broker级别的消费QPS",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (broker,brokerIP) (rocketmq_broker_qps{busigroup=~\"$busigroup\",cluster=~\"$cluster\"})",
     "legendFormat": "{{brokerIP}}  {{broker}}"
    }
   ]
  },
  {
   "title": "Broker级别的生产TPS",
   "type": "timeseries",
   "description": "Broker级别的生产TPS",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (broker,brokerIP) (rocketmq_broker_tps{busigroup=~\"$busigroup\",cluster=~\"$cluster\"})",
     "legendFormat": " {{brokerIP}} {{broker}}"
    }
   ]
  },
  { "title": "生产端", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Topic在一个Broker组上的生产TPS (TOP 5)",
   "type": "timeseries",
   "description": "Topic在一个Broker组上的生产TPS",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5,sum(rocketmq_producer_tps{busigroup=~\"$busigroup\",cluster=~\"$cluster\"}>=1) by (topic))",
     "legendFormat": "生产者 TPS {{topic}}"
    }
   ]
  },
  {
   "title": "Topic在一个Broker组上的生产消息大小的TPS (TOP 5)",
   "type": "timeseries",
   "description": "Topic在一个Broker组上的生产消息大小的TPS",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5,sum(rocketmq_producer_message_size{busigroup=~\"$busigroup\",cluster=~\"$cluster\"}>=1) by (topic))\r\n#sum(rocketmq_producer_message_size{}>=1) by (topic)",
     "legendFormat": "生产者-{{topic}}"
    }
   ]
  },
  {
   "title": "topic当前时间的最大offset(TOP 5)",
   "type": "timeseries",
   "description": "topic当前时间的最大offset",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5,sum(rocketmq_producer_offset{busigroup=~\"$busigroup\",cluster=~\"$cluster\"}) by (broker,topic))",
     "legendFormat": "生产者 {{broker}} {{topic}}"
    }
   ]
  },
  { "title": "消费端", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "订阅组在一个broker组上消费消息大小的TPS (TOP 5)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5,sum(rocketmq_consumer_message_size{busigroup=~\"$busigroup\",cluster=~\"$cluster\"}>=1) by (topic))",
     "legendFormat": "消费者-{{topic}}"
    }
   ]
  },
  {
   "title": "每个Broker组上订阅组的消费TPS (TOP 5)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5,sum(rocketmq_consumer_tps{busigroup=~\"$busigroup\",cluster=~\"$cluster\"}>=1) by (topic))",
     "legendFormat": "消费者 TPS {{topic}}"
    }
   ]
  },
  {
   "title": "订阅组在一个broker组上当前的消费Offset(TOP 5)",
   "type": "timeseries",
   "description": "订阅组在一个broker组上当前的消费Offset",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5,sum(rocketmq_consumer_offset{busigroup=~\"$busigroup\",cluster=~\"$cluster\"}>=1) by (broker,topic))",
     "legendFormat": "消费者 {{broker}} {{topic}}"
    }
   ]
  },
  {
   "title": "消费组的消费延时时间",
   "type": "timeseries",
   "description": "{{group}} {{topic}}",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "#sort_desc(sum(rocketmq_group_get_latency_by_storetime/1000) by (broker,group,topic)) and (sum(rocketmq_group_get_latency_by_storetime) by (broker,group,topic) > 0)\r\n#(sum(rocketmq_producer_offset) by (topic) - on(topic) group_right sum(rocketmq_consumer_offset) by (group,topic)) - ignoring(group) group_left sum (avg_over_time(rocketmq_producer_tps[5m])) by (topic)*5*60 > 0\r\nrocketmq_group_get_latency_by_storetime{busigroup=~\"$busigroup\",cluster=~\"$cluster\"}[1m]/1000 > 10 and rate(rocketmq_group_get_latency_by_storetime{busigroup=~\"$busigroup\",cluster=~\"$cluster\"}[1m]) >0",
     "legendFormat": "消费组的消费延时时间 {{group}}  {{topic}}"
    }
   ]
  },
  {
   "title": "消息积压（便于复制topic）",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "# sum(rocketmq_producer_offset) by (topic) - on(topic)  group_right  sum(rocketmq_consumer_offset) by (group,topic) and (sum(rocketmq_producer_offset) by (topic) - on(topic)  group_right  sum(rocketmq_consumer_offset) by (group,topic) > 0)\r\navg by (group,topic) (rocketmq_group_diff{busigroup=~\"$busigroup\"} > 50)"
    }
   ]
  },
  {
   "title": "消息积压",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "#sum(rocketmq_producer_offset) by(topic) - on(topic) group_right sum(rocketmq_consumer_offset) by(group,topic) and (sum(rocketmq_producer_offset) by(topic) - on(topic) group_right sum(rocketmq_consumer_offset) by(group,topic) > 0)\r\n# (sum(rocketmq_producer_offset) by(topic) - on(topic) group_right sum(rocketmq_consumer_offset) by(group,topic)) - ignoring(group) group_left sum(avg_over_time(rocketmq_producer_tps[1m])) by(topic)*5*60 > 0\r\navg by (group,topic) (rocketmq_group_diff{busigroup=~\"$busigroup\"} > 50)\r\n#(sum(irate(rocketmq_producer_offset[1m])) by(topic) - on(topic) group_right sum(irate(rocketmq_consumer_offset[1m])) by (group,topic))>"
    }
   ]
  }
 ]
}